// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Put all mandatory parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Check system status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Status"
                            }
                        }
                    }
                }
            }
        },
        "/students/": {
            "post": {
                "description": "Put all mandatory parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Students"
                ],
                "summary": "Register new students",
                "parameters": [
                    {
                        "description": "CreateStudentsRequest",
                        "name": "CreateStudentsRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateStudentsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CreateStudentsResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateStudentsRequest": {
            "type": "object",
            "required": [
                "currentSemester",
                "email",
                "hoursAvailability",
                "ktmUrl",
                "major",
                "name",
                "phoneNumber",
                "residency",
                "resumeUrl",
                "role",
                "universityEmail",
                "universityName"
            ],
            "properties": {
                "currentSemester": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "githubUsername": {
                    "type": "string"
                },
                "gitlabUsername": {
                    "type": "string"
                },
                "hoursAvailability": {
                    "type": "integer"
                },
                "ktmUrl": {
                    "type": "string"
                },
                "linkedInUrl": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "projectCount": {
                    "type": "string"
                },
                "relevantCoursework": {
                    "type": "string"
                },
                "residency": {
                    "type": "string"
                },
                "resumeUrl": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "universityEmail": {
                    "type": "string"
                },
                "universityName": {
                    "type": "string"
                }
            }
        },
        "dto.CreateStudentsResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.Status": {
            "type": "object",
            "properties": {
                "data": {},
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Students-Tech Server",
	Description:      "API definition for Students Tech Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
